name: publish-to-server
on:
  push:
    branches:
      - curation
      - devel
      - staging
      - release
  workflow_dispatch:

jobs:
  generate-map:
    runs-on: ubuntu-latest
    if: github.repository == 'AnatomicMaps/vagus-nerve-flatmap'
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install remotemaker
        run: |
          python -m pip install ${{ vars.REMOTE_MAKER_WHEEL }}
      - name: run remotemaker
        run: |
          commit=${{ github.ref_name }}
          if [[ "curation" == "${commit}" ]]; then
            server=${{ vars.CURATION_MAP_SERVER }}
            token=${{ secrets.CURATION_SERVER_TOKEN }}
          elif [[ "devel" == "${commit}" ]]; then
            server=${{ vars.DEVEL_MAP_SERVER }}
            token=${{ secrets.DEVEL_SERVER_TOKEN }}
          elif [[ "staging" == "${commit}" ]]; then
            server=${{ vars.STAGING_MAP_SERVER }}
            token=${{ secrets.STAGING_SERVER_TOKEN }}
          elif [[ "release" == "${commit}" ]]; then
            server=${{ vars.PRODUCTION_MAP_SERVER }}
            token=${{ secrets.PRODUCTION_SERVER_TOKEN }}
          fi
          python -m remotemaker \
                 --server $server \
                 --token $token \
                 --source ${{ github.server_url }}/${{ github.repository }} \
                 --manifest manifest.json \
                 --commit $commit
